version: '3'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    # volumes:
    #   - postgres-volume:/var/lib/postgresql/data
    ports:
    - 5432:5432

# volumes:
#   postgres-volume: